version: "3"
services:
  my-mongo:
    build: ./backend
    image: "austin/earth_db"
    ports:
      - "27017:27017"
  my-api:
    build: ./monolithic_rest_service
    depends_on:
      - my-mongo
    image: "austin/mono_api"
    ports:
      - "80:80"
  frontend:
    build: ./frontend
    depends_on:
      - my-mongo
      - my-api
    links:
      - my-api
    image: "austin/earth_frontend"
    ports:
      - "3000:3000"